name: msg_dashboard
description: "Painel de gerenciameto de viagens da MSA Soluções"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  firebase_core: ^3.5.0
  firebase_performance_dio: ^0.7.1
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  firebase_analytics: ^11.3.2
  firebase_crashlytics: ^4.1.2
  firebase_remote_config: ^5.1.2
  firebase_performance: ^0.10.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
